version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: octalmage
  coins:
  - 10000000000000umeep
- name: faucet
  coins:
  - 10000000000000umeep
faucet:
  name: faucet
  coins:
  - 100000000umeep
  coins_max:
  - 100000000umeep
client:
  vuex:
    path: vue/src/store
genesis:
  app_state:
    gov:
      deposit_params:
        max_deposit_period: 3600s
        min_deposit:
        - amount: "10000000"
          denom: umeep
      tally_params:
        quorum: "0.001000000000000000"
        threshold: "0.01000000000000000"
      voting_params:
        voting_period: 3600s
    mint:
      params:
        mint_denom: umeep
    staking:
      params:
        bond_denom: umeep
        max_validators: 5
  chain_id: meep-1
validators:
- name: octalmage
  bonded: 10000000000000umeep
