accounts:
  - name: octalmage
    coins: ["10000000000000umeep"]
  - name: faucet
    coins: ["10000000000000umeep"]
    # address: cosmos10tumxa8rsy4lu5q8x6f73wu4s4j7wpkk4mjwcp

validator:
  name: octalmage
  staked: "10000000000000umeep"
client:
  vuex:
    path: "vue/src/store"
genesis:
  chain_id: "meep-1"
  app_state:
    staking:
      params:
        bond_denom: "umeep"
    mint:
      params:
        mint_denom: "umeep"
    # crisis:
    #   constant_fee:
    #     denom: "meep"
    gov:
      deposit_params:
        min_deposit:
          - amount: "100000000"
            denom: "umeep" 
faucet:
  name: faucet 
  coins: ["100000000umeep"]
  coins_max: ["100000000umeep"]
  host: "159.65.103.150:4500"
host:
  rpc: "159.65.103.150:26657"
  api: "159.65.103.150:1317"
  frontend: "159.65.103.150:8888"
  dev-ui: "159.65.103.150:12345"