accounts:
  - name: octalmage
    coins: ["10000000000000umeep"]
  - name: faucet
    coins: ["10000000000000umeep"]
    # address: cosmos10tumxa8rsy4lu5q8x6f73wu4s4j7wpkk4mjwcp

validator:
  name: octalmage
  staked: "10000000000000umeep"
client:
  vuex:
    path: "vue/src/store"
genesis:
  chain_id: "meep-1"
  app_state:
    staking:
      params:
        bond_denom: "umeep"
        max_validators: 5
    mint:
      params:
        mint_denom: "umeep"
    # crisis:
    #   constant_fee:
    #     denom: "meep"
    # gov:
    #   deposit_params:
    #     # max_deposit_period: "3600000000000"
    #     # voting_period: "3600000000000"
    #     quorum: "0.001000000000000000"
    #     threshold: "0.01000000000000000"
    #     min_deposit:
    #       - amount: "10000000"
    #         denom: "umeep" 
faucet:
  name: faucet 
  coins: ["100000000umeep"]
  coins_max: ["100000000umeep"]
  host: "159.65.103.150:4500"
host:
  rpc: "159.65.103.150:26657"
  api: "159.65.103.150:1317"