version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: octalmage
  address: meep1foiwoefjweofjwoeifj
  coins:
  - 10000000000000umeep
- name: faucet
  coins:
  - 10000000000000umeep
faucet:
  name: faucet
  coins:
  - 100000000umeep
  coins_max:
  - 100000000umeep
client:
  vuex:
    path: vue/src/store
genesis:
  app_state:
    mint:
      params:
        mint_denom: umeep
    staking:
      params:
        bond_denom: umeep
        max_validators: 5
  chain_id: meep-1
validator:
- name: octalmage
  staked: 10000000000000umeep
